services:
    app:
        build:
            context: .
            dockerfile: dev.Dockerfile
            args:
                - user=userApp
        ports:
            - ${APP_PORT}:${APP_PORT}
            - ${APP_VITE_PORT}:${APP_VITE_PORT}
        env_file:
            - .env
        volumes:
            - .:/app
        networks:
            - lavapplication
        environment:
            - APP_ENV=${APP_ENV}
            - APP_PORT=${APP_PORT}
            - APP_VITE_PORT=${APP_VITE_PORT}

networks:
    lavapplication:
        driver: bridge
